#!/bin/bash

# DB Setup
createdb demo_dev

# Initial setup
mix deps.get
MIX_ENV=dev mix compile

# Compile assets
npm install --prefix ./assets
npm run deploy --prefix ./assets
mix phx.digest

# Custom tasks (like DB migrations)
MIX_ENV=dev mix ecto.migrate
